import { BUILDER2_CLASSIFICATION_DECISION, builder2Fingerprint, clean } from './contracts.js';
function uniqueNums(v=[]){return [...new Set((v||[]).map(Number).filter(Number.isFinite))];}
function nodeIdForTaxon(t){return t.canonicalNodeId||`b2_${builder2Fingerprint({taxonId:t.taxonId,label:t.label}).replace(/[^a-z0-9]/gi,'_')}`;}
function depthOf(id,byId,memo=new Map()){if(memo.has(id))return memo.get(id);const n=byId.get(id);if(!n)return 0;const d=n.parentTaxonId?1+depthOf(n.parentTaxonId,byId,memo):0;memo.set(id,d);return d;}
function parentNodeId(t,byId,nodeIds){return t.parentTaxonId?nodeIds.get(t.parentTaxonId)||null:null;}
export function buildBuilder2ProspectivePopulation({treeInventory=null,worksetSources=[],classifications=[],taxonomy}={}){
  const complete=treeInventory?.membershipComplete===true||treeInventory?.completeUidMembership===true; if(!complete)return{complete:false,uidHomes:null,duplicateUidHomes:[],reason:'existing-tree-membership-incomplete'};
  const homes=new Map();for(const n of treeInventory?.nodes||[])for(const uid of uniqueNums([...(n.uids||[]),...(n.loreUids||[]),...(n.entryUids||[])])){const s=homes.get(uid)||new Set();s.add(String(n.id));homes.set(uid,s);}
  const deferredSourceKeys=new Set((classifications||[]).filter(c=>c.metadata?.resolvedDisposition==='deferred').map(c=>c.sourceKey));
  // A deferred decision carries explicit *no new placement authority*.  Keep a
  // prior valid home if one exists; a new source simply remains unrepresented.
  // Removed sources still have negative authority and must be detached.
  const changedUids=new Set(worksetSources.filter(s=>s.removed||(!s.disabled&&!deferredSourceKeys.has(s.sourceKey))).map(s=>Number(s.uid)).filter(Number.isFinite));for(const uid of changedUids)homes.delete(uid);
  const taxa=new Map(taxonomy.nodes.map(t=>[t.taxonId,t])), nodeIds=new Map(taxonomy.nodes.map(t=>[t.taxonId,nodeIdForTaxon(t)]));
  for(const c of classifications){if(c.decision!==BUILDER2_CLASSIFICATION_DECISION.CLASSIFIED)continue;const src=worksetSources.find(s=>s.sourceKey===c.sourceKey);if(!src||src.removed||src.disabled)continue;const target=nodeIds.get(c.taxonId);if(!target||!taxa.has(c.taxonId))continue;homes.set(Number(src.uid),new Set([target]));}
  const duplicateUidHomes=[...homes.entries()].filter(([,set])=>set.size>1).map(([uid])=>uid).sort((a,b)=>a-b);const projection=[...homes.entries()].map(([uid,set])=>({uid,nodeIds:[...set].sort()})).sort((a,b)=>a.uid-b.uid);return{complete:true,uidHomes:projection,duplicateUidHomes,populationFingerprint:`population:${builder2Fingerprint(projection)}`};
}
export function createBuilder2StructuralHandoff({plan,taxonomy,classifications,worksetSources=[],treeInventory=null,baselineTaxonomy=null}={}){
  if(!plan||!taxonomy)throw new Error('Builder 2 structural handoff requires plan and taxonomy.');const byId=new Map(taxonomy.nodes.map(t=>[t.taxonId,t])), nodeIds=new Map(taxonomy.nodes.map(t=>[t.taxonId,nodeIdForTaxon(t)]));const ids=[...nodeIds.values()];if(new Set(ids).size!==ids.length)throw new Error('Builder 2 structural materialization produced duplicate canonical node IDs.');
  const baseline=new Map((baselineTaxonomy?.nodes||[]).map(t=>[t.taxonId,t])),ops=[];
  for(const t of [...taxonomy.nodes].sort((a,b)=>depthOf(a.taxonId,byId)-depthOf(b.taxonId,byId)||a.taxonId.localeCompare(b.taxonId))){const nodeId=nodeIds.get(t.taxonId),parentId=parentNodeId(t,byId,nodeIds),old=baseline.get(t.taxonId);if(!t.canonicalNodeId){ops.push({op:'create-node',taxonId:t.taxonId,nodeId,parentNodeId:parentId,label:t.label,entryPolicy:t.entryPolicy});}else if(old){const oldParent=old.parentTaxonId?nodeIds.get(old.parentTaxonId)||old.canonicalParentNodeId||null:null;if(old.label!==t.label)ops.push({op:'rename-node',taxonId:t.taxonId,nodeId,label:t.label,expectedLabel:old.label});if(oldParent!==parentId)ops.push({op:'move-node',taxonId:t.taxonId,nodeId,parentNodeId:parentId,expectedParentNodeId:oldParent});}}
  const bySource=new Map(worksetSources.map(s=>[s.sourceKey,s])),uidPlacements=[];for(const c of classifications){if(c.decision!==BUILDER2_CLASSIFICATION_DECISION.CLASSIFIED)continue;const s=bySource.get(c.sourceKey);if(!s||s.removed||s.disabled)continue;uidPlacements.push({sourceKey:s.sourceKey,uid:s.uid,sourceFingerprint:s.fingerprint,taxonId:c.taxonId,nodeId:nodeIds.get(c.taxonId)});}uidPlacements.sort((a,b)=>a.uid-b.uid||a.sourceKey.localeCompare(b.sourceKey));
  const sourceRemovals=worksetSources.filter(s=>s.removed).map(s=>({sourceKey:s.sourceKey,uid:s.uid,sourceFingerprint:s.fingerprint,reason:s.removalReason||'removed-from-corpus'})).sort((a,b)=>a.uid-b.uid);
  const sourceExclusions=classifications.filter(c=>c.metadata?.resolvedDisposition==='nonsemantic').map(c=>{const s=bySource.get(c.sourceKey);return s&&!s.removed?{sourceKey:s.sourceKey,uid:s.uid,sourceFingerprint:s.fingerprint,reason:'operator-nonsemantic'}:null;}).filter(Boolean).sort((a,b)=>a.uid-b.uid);
  const sourceDeferrals=classifications.filter(c=>c.metadata?.resolvedDisposition==='deferred').map(c=>{const s=bySource.get(c.sourceKey);return s&&!s.removed?{sourceKey:s.sourceKey,uid:s.uid,sourceFingerprint:s.fingerprint,reason:'operator-deferred',priorDecision:c.decision}:null;}).filter(Boolean).sort((a,b)=>a.uid-b.uid);
  const prospectivePopulation=buildBuilder2ProspectivePopulation({treeInventory,worksetSources,classifications,taxonomy});if(prospectivePopulation.duplicateUidHomes.length)throw new Error(`Builder 2 prospective Tree has duplicate UID homes: ${prospectivePopulation.duplicateUidHomes.join(', ')}.`);
  const core={contract:'nexus-lorebook-builder/v2-structural-handoff',runId:plan.runId,planRevision:plan.planRevision,book:plan.book,mode:plan.mode,sourceRevision:plan.sourceRevision,corpusRevision:plan.corpusRevision||plan.sourceRevision,treeRevision:plan.treeRevision||null,taxonomyRevision:taxonomy.revisionId,classificationRevision:taxonomy.classificationRevisionId,materializationRevision:taxonomy.materializationRevisionId,structuralOperations:ops,uidPlacements,sourceRemovals,sourceExclusions,sourceDeferrals,prospectivePopulation};const handoffFingerprint=`handoff:${builder2Fingerprint(core)}`;return{...core,handoffFingerprint};
}
export function validateBuilder2StructuralHandoff(handoff,{knownCorpusUids=null}={}){
  const errors=[];if(!handoff?.handoffFingerprint)errors.push('Missing immutable handoff fingerprint.');
  const createIds=(handoff?.structuralOperations||[]).filter(o=>o.op==='create-node').map(o=>o.nodeId);if(new Set(createIds).size!==createIds.length)errors.push('Duplicate create-node IDs.');
  const placementUids=(handoff?.uidPlacements||[]).map(p=>Number(p.uid)),exclusionUids=(handoff?.sourceExclusions||[]).map(p=>Number(p.uid)),removalUids=(handoff?.sourceRemovals||[]).map(p=>Number(p.uid)),deferredUids=(handoff?.sourceDeferrals||[]).map(p=>Number(p.uid));
  if(new Set(placementUids).size!==placementUids.length)errors.push('Duplicate UID placements.');if(new Set(deferredUids).size!==deferredUids.length)errors.push('Duplicate UID deferrals.');
  const authoritative=new Set([...placementUids,...exclusionUids,...removalUids]);for(const uid of deferredUids)if(authoritative.has(uid))errors.push(`Deferred UID ${uid} also has conflicting placement/removal/exclusion authority.`);
  if(knownCorpusUids){const known=new Set(knownCorpusUids.map(Number));for(const p of handoff.uidPlacements||[])if(!known.has(Number(p.uid)))errors.push(`Dangling UID placement ${p.uid}.`);for(const p of handoff.sourceDeferrals||[])if(!known.has(Number(p.uid)))errors.push(`Dangling UID deferral ${p.uid}.`);}
  return{passed:errors.length===0,errors};
}
